# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: segment.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='segment.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n$com.qd.nlp.springcloud.proto.segmentB\013TextSegmentP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsegment.proto\"*\n\nWordNature\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0e\n\x06nature\x18\x02 \x01(\t\"4\n\x11\x44ictionaryRequest\x12\x1f\n\nwordNature\x18\x01 \x03(\x0b\x32\x0b.WordNature\"$\n\x12\x44ictionaryResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\"R\n\x0eSegmentRequest\x12\x1f\n\nwordNature\x18\x01 \x03(\x0b\x32\x0b.WordNature\x12\x0c\n\x04text\x18\x02 \x03(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\"4\n\x11SegmentWordNature\x12\x1f\n\nwordNature\x18\x01 \x03(\x0b\x32\x0b.WordNature\"6\n\x0fSegmentResponse\x12#\n\x07segment\x18\x01 \x03(\x0b\x32\x12.SegmentWordNature\"#\n\x10HeartbeatRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"%\n\x11HeartbeatResponse\x12\x10\n\x08response\x18\x01 \x01(\t2\xf1\x01\n\x12TextSegmentService\x12:\n\x0f\x61\x64\x64\x45xternalWord\x12\x12.DictionaryRequest\x1a\x13.DictionaryResponse\x12=\n\x12removeExternalWord\x12\x12.DictionaryRequest\x1a\x13.DictionaryResponse\x12,\n\x07segment\x12\x0f.SegmentRequest\x1a\x10.SegmentResponse\x12\x32\n\theartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponseB5\n$com.qd.nlp.springcloud.proto.segmentB\x0bTextSegmentP\x01\x62\x06proto3'
)




_WORDNATURE = _descriptor.Descriptor(
  name='WordNature',
  full_name='WordNature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='WordNature.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nature', full_name='WordNature.nature', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=59,
)


_DICTIONARYREQUEST = _descriptor.Descriptor(
  name='DictionaryRequest',
  full_name='DictionaryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordNature', full_name='DictionaryRequest.wordNature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=113,
)


_DICTIONARYRESPONSE = _descriptor.Descriptor(
  name='DictionaryResponse',
  full_name='DictionaryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='DictionaryResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=151,
)


_SEGMENTREQUEST = _descriptor.Descriptor(
  name='SegmentRequest',
  full_name='SegmentRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordNature', full_name='SegmentRequest.wordNature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='SegmentRequest.text', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='SegmentRequest.namespace', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=235,
)


_SEGMENTWORDNATURE = _descriptor.Descriptor(
  name='SegmentWordNature',
  full_name='SegmentWordNature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='wordNature', full_name='SegmentWordNature.wordNature', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=289,
)


_SEGMENTRESPONSE = _descriptor.Descriptor(
  name='SegmentResponse',
  full_name='SegmentResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='segment', full_name='SegmentResponse.segment', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=345,
)


_HEARTBEATREQUEST = _descriptor.Descriptor(
  name='HeartbeatRequest',
  full_name='HeartbeatRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request', full_name='HeartbeatRequest.request', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=382,
)


_HEARTBEATRESPONSE = _descriptor.Descriptor(
  name='HeartbeatResponse',
  full_name='HeartbeatResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='HeartbeatResponse.response', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=384,
  serialized_end=421,
)

_DICTIONARYREQUEST.fields_by_name['wordNature'].message_type = _WORDNATURE
_SEGMENTREQUEST.fields_by_name['wordNature'].message_type = _WORDNATURE
_SEGMENTWORDNATURE.fields_by_name['wordNature'].message_type = _WORDNATURE
_SEGMENTRESPONSE.fields_by_name['segment'].message_type = _SEGMENTWORDNATURE
DESCRIPTOR.message_types_by_name['WordNature'] = _WORDNATURE
DESCRIPTOR.message_types_by_name['DictionaryRequest'] = _DICTIONARYREQUEST
DESCRIPTOR.message_types_by_name['DictionaryResponse'] = _DICTIONARYRESPONSE
DESCRIPTOR.message_types_by_name['SegmentRequest'] = _SEGMENTREQUEST
DESCRIPTOR.message_types_by_name['SegmentWordNature'] = _SEGMENTWORDNATURE
DESCRIPTOR.message_types_by_name['SegmentResponse'] = _SEGMENTRESPONSE
DESCRIPTOR.message_types_by_name['HeartbeatRequest'] = _HEARTBEATREQUEST
DESCRIPTOR.message_types_by_name['HeartbeatResponse'] = _HEARTBEATRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WordNature = _reflection.GeneratedProtocolMessageType('WordNature', (_message.Message,), {
  'DESCRIPTOR' : _WORDNATURE,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:WordNature)
  })
_sym_db.RegisterMessage(WordNature)

DictionaryRequest = _reflection.GeneratedProtocolMessageType('DictionaryRequest', (_message.Message,), {
  'DESCRIPTOR' : _DICTIONARYREQUEST,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:DictionaryRequest)
  })
_sym_db.RegisterMessage(DictionaryRequest)

DictionaryResponse = _reflection.GeneratedProtocolMessageType('DictionaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _DICTIONARYRESPONSE,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:DictionaryResponse)
  })
_sym_db.RegisterMessage(DictionaryResponse)

SegmentRequest = _reflection.GeneratedProtocolMessageType('SegmentRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTREQUEST,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:SegmentRequest)
  })
_sym_db.RegisterMessage(SegmentRequest)

SegmentWordNature = _reflection.GeneratedProtocolMessageType('SegmentWordNature', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTWORDNATURE,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:SegmentWordNature)
  })
_sym_db.RegisterMessage(SegmentWordNature)

SegmentResponse = _reflection.GeneratedProtocolMessageType('SegmentResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTRESPONSE,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:SegmentResponse)
  })
_sym_db.RegisterMessage(SegmentResponse)

HeartbeatRequest = _reflection.GeneratedProtocolMessageType('HeartbeatRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATREQUEST,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:HeartbeatRequest)
  })
_sym_db.RegisterMessage(HeartbeatRequest)

HeartbeatResponse = _reflection.GeneratedProtocolMessageType('HeartbeatResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEARTBEATRESPONSE,
  '__module__' : 'segment_pb2'
  # @@protoc_insertion_point(class_scope:HeartbeatResponse)
  })
_sym_db.RegisterMessage(HeartbeatResponse)


DESCRIPTOR._options = None

_TEXTSEGMENTSERVICE = _descriptor.ServiceDescriptor(
  name='TextSegmentService',
  full_name='TextSegmentService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=424,
  serialized_end=665,
  methods=[
  _descriptor.MethodDescriptor(
    name='addExternalWord',
    full_name='TextSegmentService.addExternalWord',
    index=0,
    containing_service=None,
    input_type=_DICTIONARYREQUEST,
    output_type=_DICTIONARYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='removeExternalWord',
    full_name='TextSegmentService.removeExternalWord',
    index=1,
    containing_service=None,
    input_type=_DICTIONARYREQUEST,
    output_type=_DICTIONARYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='segment',
    full_name='TextSegmentService.segment',
    index=2,
    containing_service=None,
    input_type=_SEGMENTREQUEST,
    output_type=_SEGMENTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='heartbeat',
    full_name='TextSegmentService.heartbeat',
    index=3,
    containing_service=None,
    input_type=_HEARTBEATREQUEST,
    output_type=_HEARTBEATRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXTSEGMENTSERVICE)

DESCRIPTOR.services_by_name['TextSegmentService'] = _TEXTSEGMENTSERVICE

# @@protoc_insertion_point(module_scope)
